[package]
name = "age-plugin"
description = "[BETA] API for writing age plugins."
version = "0.0.0"
authors = ["Jack Grigg <thestr4d@gmail.com>"]
repository = "https://github.com/str4d/rage"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
age-core = { version = "0.4.0", path = "../age-core", features = ["plugin"] }
bech32 = "0.7.2"
chrono = "0.4"
secrecy = "0.7"

[dev-dependencies]
gumdrop = "0.8"
