
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[imports.zcash.criteria-map]
ours = "crypto-reviewed"
theirs = "crypto-reviewed"

[policy.age]
audit-as-crates-io = false

[policy.age-core]
audit-as-crates-io = false

[policy.age-plugin]
audit-as-crates-io = false

[policy.rage]
audit-as-crates-io = false

[[exemptions.aead]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.aes-gcm]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.anstream]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.8"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.arc-swap]]
version = "1.7.1"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.73"
criteria = "safe-to-run"

[[exemptions.base64ct]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.bcrypt-pbkdf]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.bech32]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.block-padding]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.blowfish]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.bzip2]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.bzip2-sys]]
version = "0.1.13+1.0.8"
criteria = "safe-to-deploy"

[[exemptions.cbc]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.33"
criteria = "safe-to-deploy"

[[exemptions.chacha20]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.chacha20poly1305]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.39"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.3.24"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.3.24"
criteria = "safe-to-deploy"

[[exemptions.clap_complete]]
version = "4.3.2"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.3.12"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.clap_mangen]]
version = "0.2.12"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.console]]
version = "0.15.8"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.constant_time_eq]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.content_inspector]]
version = "0.2.4"
criteria = "safe-to-run"

[[exemptions.cookie-factory]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.3.6"
criteria = "safe-to-run"

[[exemptions.criterion-cycles-per-byte]]
version = "0.6.1"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.4.5"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.ctr]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.ctrlc]]
version = "3.4.2"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "4.1.0"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek-derive]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.dunce]]
version = "1.0.5"
criteria = "safe-to-run"

[[exemptions.encode_unicode]]
version = "0.3.6"
criteria = "safe-to-deploy"

[[exemptions.env_logger]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.filetime]]
version = "0.2.25"
criteria = "safe-to-deploy"

[[exemptions.find-crate]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.findshlibs]]
version = "0.10.2"
criteria = "safe-to-run"

[[exemptions.fuse_mt]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.fuser]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.25"
criteria = "safe-to-deploy"

[[exemptions.futures-test]]
version = "0.3.31"
criteria = "safe-to-run"

[[exemptions.futures-util]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.6"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.10"
criteria = "safe-to-deploy"

[[exemptions.ghash]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.glob]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.15.5"
criteria = "safe-to-run"

[[exemptions.hermit-abi]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.hkdf]]
version = "0.12.4"
criteria = "safe-to-deploy"

[[exemptions.home]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.humantime-serde]]
version = "1.1.1"
criteria = "safe-to-run"

[[exemptions.i18n-config]]
version = "0.4.8"
criteria = "safe-to-deploy"

[[exemptions.i18n-embed]]
version = "0.16.0"
criteria = "safe-to-deploy"

[[exemptions.i18n-embed-fl]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.i18n-embed-impl]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.10.0"
criteria = "safe-to-run"

[[exemptions.inferno]]
version = "0.11.17"
criteria = "safe-to-run"

[[exemptions.io_tee]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.is-terminal]]
version = "0.4.16"
criteria = "safe-to-deploy"

[[exemptions.jobserver]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.76"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.175"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.4.15"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.6.3"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.nix]]
version = "0.26.1"
criteria = "safe-to-deploy"

[[exemptions.num-bigint-dig]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.num-format]]
version = "0.4.4"
criteria = "safe-to-run"

[[exemptions.num_cpus]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.7"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.os_pipe]]
version = "1.2.2"
criteria = "safe-to-run"

[[exemptions.page_size]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.2"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.11"
criteria = "safe-to-deploy"

[[exemptions.password-hash]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.pbkdf2]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.pbkdf2]]
version = "0.12.2"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.5"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.pkcs1]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.poly1305]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.polyval]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.pprof]]
version = "0.13.0"
criteria = "safe-to-run"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error-attr2]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error2]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.proptest]]
version = "1.6.0"
criteria = "safe-to-run"

[[exemptions.quick-xml]]
version = "0.26.0"
criteria = "safe-to-run"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.17"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.9.5"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.rgb]]
version = "0.8.52"
criteria = "safe-to-run"

[[exemptions.roff]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.rpassword]]
version = "7.4.0"
criteria = "safe-to-deploy"

[[exemptions.rsa]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.rtoolbox]]
version = "0.0.3"
criteria = "safe-to-deploy"

[[exemptions.rust-embed]]
version = "8.3.0"
criteria = "safe-to-deploy"

[[exemptions.rust-embed-impl]]
version = "8.3.0"
criteria = "safe-to-deploy"

[[exemptions.rust-embed-utils]]
version = "8.3.0"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.38.44"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "1.0.8"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.22"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.15"
criteria = "safe-to-run"

[[exemptions.salsa20]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.scrypt]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.secrecy]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.self_cell]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.serde_spanned]]
version = "0.6.8"
criteria = "safe-to-run"

[[exemptions.slab]]
version = "0.4.11"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.15.1"
criteria = "safe-to-deploy"

[[exemptions.snapbox]]
version = "0.4.11"
criteria = "safe-to-run"

[[exemptions.snapbox-macros]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.str_stack]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.symbolic-common]]
version = "12.13.1"
criteria = "safe-to-run"

[[exemptions.symbolic-demangle]]
version = "12.13.1"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "2.0.106"
criteria = "safe-to-deploy"

[[exemptions.sys-locale]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tar]]
version = "0.4.44"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.termcolor]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.test-case]]
version = "3.3.1"
criteria = "safe-to-run"

[[exemptions.test-case-core]]
version = "3.3.1"
criteria = "safe-to-run"

[[exemptions.test-case-macros]]
version = "3.3.1"
criteria = "safe-to-run"

[[exemptions.thiserror]]
version = "2.0.16"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.16"
criteria = "safe-to-deploy"

[[exemptions.threadpool]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.1.44"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.38.2"
criteria = "safe-to-run"

[[exemptions.tokio-macros]]
version = "2.3.0"
criteria = "safe-to-run"

[[exemptions.toml]]
version = "0.5.9"
criteria = "safe-to-deploy"

[[exemptions.toml_edit]]
version = "0.19.14"
criteria = "safe-to-run"

[[exemptions.trycmd]]
version = "0.14.16"
criteria = "safe-to-run"

[[exemptions.type-map]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-run"

[[exemptions.uuid]]
version = "1.18.0"
criteria = "safe-to-run"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.walkdir]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.14.2+wasi-0.2.4"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.99"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.99"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.65"
criteria = "safe-to-deploy"

[[exemptions.which]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-implement]]
version = "0.58.0"
criteria = "safe-to-deploy"

[[exemptions.windows-result]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.winnow]]
version = "0.5.40"
criteria = "safe-to-run"

[[exemptions.wsl]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.x25519-dalek]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.xattr]]
version = "1.5.1"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.6.6"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.7.35"
criteria = "safe-to-run"

[[exemptions.zerocopy]]
version = "0.8.26"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.6.6"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.35"
criteria = "safe-to-run"

[[exemptions.zerocopy-derive]]
version = "0.8.26"
criteria = "safe-to-deploy"

[[exemptions.zip]]
version = "0.6.6"
criteria = "safe-to-deploy"

[[exemptions.zstd]]
version = "0.11.2+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-safe]]
version = "5.0.2+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-sys]]
version = "2.0.15+zstd.1.5.7"
criteria = "safe-to-deploy"
